/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author TuanTuti
 */
public class frmQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLy
     */
    public frmQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        thongkebtn = new javax.swing.JMenu();
        giaovienbtn = new javax.swing.JMenu();
        monhocbtn = new javax.swing.JMenu();
        sinhvienbtn = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jPanel4.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), null, new java.awt.Color(102, 0, 0), new java.awt.Color(204, 204, 0)));

        thongkebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Bar chart.png"))); // NOI18N
        thongkebtn.setText("Thống kê");
        thongkebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongkebtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(thongkebtn);

        giaovienbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Conference.png"))); // NOI18N
        giaovienbtn.setText("Giáo viên");
        jMenuBar1.add(giaovienbtn);

        monhocbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Address book.png"))); // NOI18N
        monhocbtn.setText("Môn học");
        monhocbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monhocbtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(monhocbtn);

        sinhvienbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Clien list.png"))); // NOI18N
        sinhvienbtn.setText("Sinh viên");
        sinhvienbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinhvienbtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(sinhvienbtn);

        mnuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/dangxuat.png"))); // NOI18N
        mnuDangXuat.setText("Đăng Xuất");
        mnuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDangXuatMouseClicked(evt);
            }
        });
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuDangXuat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDangXuatMouseClicked
        // TODO add your handling code here:
        confirm();
        
    }//GEN-LAST:event_mnuDangXuatMouseClicked

    private void monhocbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monhocbtnMouseClicked
        // TODO add your handling code here:
//        frmGioiThieu frmgt = new frmGioiThieu();
//        frmgt.show();
    }//GEN-LAST:event_monhocbtnMouseClicked

    private void thongkebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkebtnMouseClicked
        // TODO add your handling code here:
//        frmQuanLy frmql = new frmQuanLy();
//        frmql.show();
//        this.dispose();
    }//GEN-LAST:event_thongkebtnMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//        int kQ = JOptionPane.showConfirmDialog(null,
//                "Bạn có muốn thoát chương trình không ?","Confirm",JOptionPane.YES_NO_OPTION);
//        if(kQ == 0){
//            Main.playSound("soundbutton.wav");
//            System.exit(0);
//        }
//        else{
//            Main.playSound("soundbutton.wav");
//        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
//        lblHienThiUser.setText("Đăng nhập bằng tài khoản:  " + Main.hienThiTenNguoiDung);
//        lblLuotDangNhap.setText("Lượt đăng nhập:  " +Main.LuotDangNhap);
//        
//        if(frmDangNhap.Quyen == 1){
//            lblThongBao.setText("Bạn vừa đăng nhập bằng quyền ADMIN");
//        }
//        else if(frmDangNhap.Quyen == 2){
//            lblThongBao.setText("Bạn vừa đăng nhập bằng quyền IT");
//            btnQuanLyNguoiDung.setEnabled(false);
//            btnQuanLyQuyen.setEnabled(false);
//        }
//        else if(frmDangNhap.Quyen == 3){
//            lblThongBao.setText("Bạn vừa đăng nhập bằng quyền Nhân Viên");
//            btnBangNhanVien.setEnabled(false);
//            btnQuanLyNguoiDung.setEnabled(false);
//            btnQuanLyQuyen.setEnabled(false);
//            btnBangLoaiSanPham.setEnabled(false);
//        }
    }//GEN-LAST:event_formWindowOpened

    private void sinhvienbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhvienbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sinhvienbtnMouseClicked
    public void confirm(){
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn đăng xuất không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            frmDangNhap frmdn = new frmDangNhap();
            frmdn.show();
            this.dispose();
        }
        else{
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu giaovienbtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu mnuDangXuat;
    private javax.swing.JMenu monhocbtn;
    private javax.swing.JMenu sinhvienbtn;
    private javax.swing.JMenu thongkebtn;
    // End of variables declaration//GEN-END:variables
}
