/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SinhVien;

import GUI.frmSinhVien;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TuanTuti
 */
public class frmDangKiDiem extends javax.swing.JFrame {
    Connection con, con1;
    private String id_sv_23, maLHP_DK_23;
    int hangBang_23;
    /**
     * Creates new form frmLoaiSanPham
     */
    public frmDangKiDiem(String idSv) {
        initComponents();
        this.id_sv_23 = idSv;
//        LayDuLieu("221");
    }

    private frmDangKiDiem() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlform = new javax.swing.JPanel();
        lblMaLoaiSP = new javax.swing.JLabel();
        lblTenLoai = new javax.swing.JLabel();
        tenHocPhan = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        malhp = new javax.swing.JLabel();
        maTinChi = new javax.swing.JLabel();
        lblTimKiem1 = new javax.swing.JLabel();
        lblTimKiem2 = new javax.swing.JLabel();
        thoigianlb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangDiem = new javax.swing.JTable();
        tieudelb = new javax.swing.JLabel();
        btnDaDK = new javax.swing.JButton();
        btnChuaDK = new javax.swing.JButton();
        btnDangKi = new javax.swing.JButton();
        btnHuyDangKi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlform.setBackground(new java.awt.Color(204, 204, 204));
        pnlform.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlform.setForeground(new java.awt.Color(0, 255, 0));

        lblMaLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaLoaiSP.setForeground(new java.awt.Color(0, 102, 102));
        lblMaLoaiSP.setText("Mã LHP");

        lblTenLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenLoai.setForeground(new java.awt.Color(0, 153, 0));
        lblTenLoai.setText("Mã tín chỉ");

        tenHocPhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenHocPhan.setForeground(new java.awt.Color(102, 102, 102));
        tenHocPhan.setText("Tên HP");

        btnQuayLai.setForeground(new java.awt.Color(255, 0, 0));
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.png"))); // NOI18N
        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        malhp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        malhp.setForeground(new java.awt.Color(0, 102, 102));
        malhp.setText("Mã LHP");

        maTinChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maTinChi.setForeground(new java.awt.Color(0, 153, 0));
        maTinChi.setText("Mã tín chỉ");

        lblTimKiem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimKiem1.setForeground(new java.awt.Color(102, 102, 102));
        lblTimKiem1.setText("Tên HP");

        lblTimKiem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimKiem2.setForeground(new java.awt.Color(255, 102, 102));
        lblTimKiem2.setText("Thời gian");

        thoigianlb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thoigianlb.setForeground(new java.awt.Color(255, 102, 102));
        thoigianlb.setText("Thời gian");

        javax.swing.GroupLayout pnlformLayout = new javax.swing.GroupLayout(pnlform);
        pnlform.setLayout(pnlformLayout);
        pnlformLayout.setHorizontalGroup(
            pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLai)
                    .addGroup(pnlformLayout.createSequentialGroup()
                        .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaLoaiSP)
                            .addComponent(lblTimKiem1)
                            .addComponent(lblTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTimKiem2))
                        .addGap(23, 23, 23)
                        .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thoigianlb, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(malhp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tenHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(maTinChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlformLayout.setVerticalGroup(
            pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlformLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenLoai)
                    .addComponent(maTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaLoaiSP)
                    .addComponent(malhp))
                .addGap(21, 21, 21)
                .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoigianlb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(129, 191, 141));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbBangDiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbBangDiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbBangDiem.setForeground(new java.awt.Color(0, 0, 204));
        tbBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã lớp học phần", "Tên học phần", "Mã tín chỉ", "Thời gian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBangDiem.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbBangDiem.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tbBangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBangDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBangDiem);
        if (tbBangDiem.getColumnModel().getColumnCount() > 0) {
            tbBangDiem.getColumnModel().getColumn(0).setMinWidth(20);
        }

        tieudelb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tieudelb.setForeground(new java.awt.Color(0, 0, 204));
        tieudelb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/sanpham.png"))); // NOI18N
        tieudelb.setText("Danh sách học phần đã đăng kí");

        btnDaDK.setForeground(new java.awt.Color(0, 0, 204));
        btnDaDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/pencil-red-icon.png"))); // NOI18N
        btnDaDK.setText("Đã ĐK");
        btnDaDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaDKActionPerformed(evt);
            }
        });

        btnChuaDK.setForeground(new java.awt.Color(255, 0, 0));
        btnChuaDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/user-male-edit-icon.png"))); // NOI18N
        btnChuaDK.setText("Chưa ĐK");
        btnChuaDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuaDKActionPerformed(evt);
            }
        });

        btnDangKi.setForeground(new java.awt.Color(0, 0, 204));
        btnDangKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/user-male-edit-icon.png"))); // NOI18N
        btnDangKi.setText("Đăng kí");
        btnDangKi.setEnabled(false);
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        btnHuyDangKi.setForeground(new java.awt.Color(0, 0, 204));
        btnHuyDangKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/exit.png"))); // NOI18N
        btnHuyDangKi.setText("Hủy ĐK");
        btnHuyDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDangKiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tieudelb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnHuyDangKi)
                        .addGap(18, 18, 18)
                        .addComponent(btnDangKi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDaDK)
                        .addGap(27, 27, 27)
                        .addComponent(btnChuaDK)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieudelb)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaDK)
                    .addComponent(btnChuaDK)
                    .addComponent(btnDangKi)
                    .addComponent(btnHuyDangKi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String kiemtraDauvaoLoc (String dauvao_23) {
        if ("".equals(dauvao_23)) {
            dauvao_23 = "IS NOT NULL";
        }
        else {
            dauvao_23 = " = " + dauvao_23;
        }
        return dauvao_23;
    }
    
    
    // ===================== DANH SÁCH MÔN ĐÃ ĐĂNG KÍ ========================
    // ================================================================================
    // ================================================================================

    private void LayDuLieu(){
        
        con = (Connection) Db.DBConnection.ConnetionDB();
        
        try {
            Statement stm = (Statement) con.createStatement();
            
            
            String cauTruyVan = "select lhp.matc, lhp.malhp, lhp.tenlhp, lhp.tg "
                              + "from diemdk, lhp "
                              + "where masv = " + id_sv_23
                              + " and lhp.maki = 221"
                              + " and lhp.malhp = diemdk.malhp";
            System.out.println("CauTruyVan: " + cauTruyVan);
            ResultSet rs = stm.executeQuery(cauTruyVan);
            
            Object [] obj = new Object[] {"STT","Mã tín chỉ", "Mã học phần", "Tên học phần", "Thời gian"};
            DefaultTableModel tableModel = new DefaultTableModel(obj,0);
            tbBangDiem.setModel(tableModel);
            
            while (rs.next()) {
                Object[] item = new Object[5];
                item[0] = tbBangDiem.getRowCount() + 1;
                item[1] = rs.getString("matc");
                item[2] = rs.getString("malhp");
                item[3] = rs.getString("tenlhp");
                item[4] = rs.getString("tg");
                tableModel.addRow(item);
            }
            
            rs.close();
            stm.close();
            
        } catch (SQLException ex) {
            //tbBangDiem.removeAll();
            GUI.Main.thongBao("Không tìm thấy dữ liệu phù hợp !!!", "Thông Báo", 1);
        }
    }
    
    
    
    // ===================== DANH SÁCH MÔN CHƯA ĐĂNG KÍ ========================
    // ================================================================================
    // ================================================================================
    private void LHPchuaDangKi(){
        
        con = (Connection) Db.DBConnection.ConnetionDB();
        
        try {
            Statement stm = (Statement) con.createStatement();
            
            String cauTruyVan = "select lhp.matc, lhp.malhp, lhp.tenlhp, lhp.tg "
                              + "from lhp "
                              + "EXCEPT"
                              + "(select lhp.matc, lhp.malhp, lhp.tenlhp, lhp.tg "
                              + "from diemdk, lhp "
                              + "where masv = " + id_sv_23
                              + " and lhp.maki = 221"
                              + " and lhp.malhp = diemdk.malhp)";
            System.out.println("CauTruyVan: " + cauTruyVan);
            ResultSet rs = stm.executeQuery(cauTruyVan);
            
            Object [] obj = new Object[] {"STT","Mã tín chỉ", "Mã học phần", "Tên học phần", "Thời gian"};
            DefaultTableModel tableModel = new DefaultTableModel(obj,0);
            tbBangDiem.setModel(tableModel);
            
            while (rs.next()) {
                Object[] item = new Object[5];
                item[0] = tbBangDiem.getRowCount() + 1;
                item[1] = rs.getString("matc");
                item[2] = rs.getString("malhp");
                item[3] = rs.getString("tenlhp");
                item[4] = rs.getString("tg");
                tableModel.addRow(item);
            }
            
            rs.close();
            stm.close();
            
        } catch (SQLException ex) {
            //tbBangDiem.removeAll();
            GUI.Main.thongBao("Không tìm thấy dữ liệu phù hợp !!!", "Thông Báo", 1);
        }
    }
    
    // ===================== ĐĂNG KÍ MÔN HỌC ========================
    // ================================================================================
    // ================================================================================
    public void capNhapMonDangKi (String maLhp) {
      try {
          String SQL = "INSERT INTO `diemdk` (`masv`, `malhp`) VALUES ('" +id_sv_23 + "', '" + maLhp + "')";
          con = (Connection) Db.DBConnection.ConnetionDB();
          Db.DBConnection.ExcuteQueryUpdateDB(con, SQL);
          GUI.Main.thongBao("Đăng kí môn học thành công !!!", "Thông Báo", 1);
      } catch (Exception e) {
          GUI.Main.thongBao("Lỗi phần đăng kí !!!", "Thông Báo", 1);
      }
    }
    
    
    // ===================== Hủy ĐĂNG KÍ MÔN HỌC ========================
    // ================================================================================
    // ================================================================================
    public void huyDangKiMonHoc (String maLhp) {
      try {
          String SQL = "delete from `diemdk` where masv = " + id_sv_23 + " and malhp = " + maLHP_DK_23;
          con = (Connection) Db.DBConnection.ConnetionDB();
          Db.DBConnection.ExcuteQueryUpdateDB(con, SQL);
          GUI.Main.thongBao("Hủy đăng kí môn học thành công !!!", "Thông Báo", 1);
      } catch (Exception e) {
          GUI.Main.thongBao("Lỗi phần hủy đăng kí !!!", "Thông Báo", 1);
      }
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LayDuLieu();
        btnDangKi.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void tbBangDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBangDiemMouseClicked
        // TODO add your handling code here:

            JTable source_23 = (JTable)evt.getSource();
            int row_23 = source_23.rowAtPoint( evt.getPoint() );
            
            Object malhp_23 = source_23.getModel().getValueAt(row_23, 2);
            Object matc_23 = source_23.getModel().getValueAt(row_23, 1);
            String tenlhp_23 = source_23.getModel().getValueAt(row_23, 3).toString();
            String tgian_23 = source_23.getModel().getValueAt(row_23, 4).toString();
            
            
            // GẮN MALHP == ĐỂ NẾU CẦN THÌ LẤY ĐK
            maLHP_DK_23 = malhp_23.toString();


            
            // XÉT GIÁ TRỊ VÀO LABEL
            malhp.setText(malhp_23.toString());
            maTinChi.setText(matc_23.toString());
            tenHocPhan.setText(tenlhp_23);
            thoigianlb.setText(tgian_23);
           
    }//GEN-LAST:event_tbBangDiemMouseClicked

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmSinhVien frmSinhVien = new frmSinhVien(id_sv_23);
        frmSinhVien.show();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn đăng kí môn này không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            capNhapMonDangKi(maLHP_DK_23);
            LHPchuaDangKi();
        }   
        else{
            GUI.Main.thongBao("Chưa xác nhận đăng kí !!!", "Thông Báo", 1);
        }
    }//GEN-LAST:event_btnDangKiActionPerformed

    private void btnDaDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaDKActionPerformed
        // TODO add your handling code here:
        LayDuLieu();
        // ENABLE NÚT ĐĂNG KÍ
        btnDangKi.setEnabled(false);
        btnHuyDangKi.setEnabled(true);
        
        // SỬA LẠI TIÊU ĐỀ
        tieudelb.setText("Danh sách học phần đã đăng kí");
    }//GEN-LAST:event_btnDaDKActionPerformed

    private void btnChuaDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuaDKActionPerformed
        // TODO add your handling code here:
        LHPchuaDangKi();
        // ENABLE NÚT ĐĂNG KÍ
        btnDangKi.setEnabled(true);
        btnHuyDangKi.setEnabled(false);
        
        // SỬA LẠI TIÊU ĐỀ
        tieudelb.setText("Danh sách học phần chưa đăng kí");
    }//GEN-LAST:event_btnChuaDKActionPerformed

    private void btnHuyDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDangKiActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn hủy đăng kí môn này không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            huyDangKiMonHoc(maLHP_DK_23);
            LayDuLieu();
        }   
        else{
            GUI.Main.thongBao("Hủy xác nhận đăng kí !!!", "Thông Báo", 1);
        }
    }//GEN-LAST:event_btnHuyDangKiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangKiDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangKiDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangKiDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangKiDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmDangKiDiem().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuaDK;
    private javax.swing.JButton btnDaDK;
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnHuyDangKi;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaLoaiSP;
    private javax.swing.JLabel lblTenLoai;
    private javax.swing.JLabel lblTimKiem1;
    private javax.swing.JLabel lblTimKiem2;
    private javax.swing.JLabel maTinChi;
    private javax.swing.JLabel malhp;
    private javax.swing.JPanel pnlform;
    private javax.swing.JTable tbBangDiem;
    private javax.swing.JLabel tenHocPhan;
    private javax.swing.JLabel thoigianlb;
    private javax.swing.JLabel tieudelb;
    // End of variables declaration//GEN-END:variables
}
