/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SinhVien;

import GUI.frmSinhVien;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Admin
 */
public class frmDoiMK extends javax.swing.JFrame {
    Connection con;
    private String id_sv_23, mkCu;

    /**
     * Creates new form frmDoiMK
     */
    public frmDoiMK(String idSV) {
        initComponents();
        this.id_sv_23 = idSV;
        layMatKhauCu();
    }

    private frmDoiMK() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    // ========= LẤY MẬT KHẨU CŨ ==================
    public String layMatKhauCu () {
        con = (Connection) Db.DBConnection.ConnetionDB();
        
        try {
            Statement stm = (Statement) con.createStatement();
            String cauTruyVan = "select * from sv";
            ResultSet rs = stm.executeQuery(cauTruyVan);
            
            while (rs.next()) {
                if (id_sv_23.equals(rs.getString(1))){
                    mkCu = rs.getString("mk");
                    System.out.println("MK cũ lấy được: " + mkCu);
                }
            }
            
            rs.close();
            stm.close();
            
        } catch (SQLException ex) {
            System.err.println("Lỗi ở ĐỔI MẬT KHẨU");
        }
        return mkCu;
    }
    
    
    // ========= CẬP NHẬP MẬT KHẨU ==================
    public boolean capNhapMK (String mkMoi) {
        try {
            String SQL = "update sv set mk = N'"+mkMoi+"'" + " where masv = "+id_sv_23;
            con = (Connection) Db.DBConnection.ConnetionDB();
            Db.DBConnection.ExcuteQueryUpdateDB(con, SQL);
            GUI.Main.thongBao("Cập nhập mật khẩu thành công !!!", "Thông Báo", 1);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnxacNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mkCuTxt = new javax.swing.JPasswordField();
        mkMoiTxt = new javax.swing.JPasswordField();
        xnMkNoiTxt = new javax.swing.JPasswordField();
        btnQuaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnxacNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnxacNhan.setForeground(new java.awt.Color(0, 0, 255));
        btnxacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update.png"))); // NOI18N
        btnxacNhan.setText("Xác nhận đổi");
        btnxacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacNhanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/secrecy-icon.png"))); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Xác nhận mật khẩu mới");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mật khẩu cũ");

        mkCuTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkCuTxtActionPerformed(evt);
            }
        });

        mkMoiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkMoiTxtActionPerformed(evt);
            }
        });

        xnMkNoiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xnMkNoiTxtActionPerformed(evt);
            }
        });

        btnQuaylai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnQuaylai.setForeground(new java.awt.Color(255, 51, 51));
        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.png"))); // NOI18N
        btnQuaylai.setText("BACK");
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mkMoiTxt)
                    .addComponent(mkCuTxt)
                    .addComponent(xnMkNoiTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnxacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mkCuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mkMoiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xnMkNoiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnxacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(298, Short.MAX_VALUE)
                    .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnxacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacNhanActionPerformed
        // TODO add your handling code here:
        String mkCuNhap = mkCuTxt.getText();
        String mkMoi = mkMoiTxt.getText();
        String mkMoiXn = xnMkNoiTxt.getText();

        System.out.println("so sanh mk: " + mkCu.equals(mkCuNhap));
        
        
        if("".equals(mkCuNhap)){           
            GUI.Main.thongBao("Mật khẩu không được bỏ trống", "Thông Báo", 1);
            mkMoiTxt.requestFocus();
        }
        else if("".equals(mkMoi)){           
            GUI.Main.thongBao("Mật khẩu không được bỏ trống", "Thông Báo", 1);
            mkCuTxt.requestFocus();
        }
        else if("".equals(mkMoiXn)){           
            GUI.Main.thongBao("Mật khẩu không được bỏ trống", "Thông Báo", 1);
            xnMkNoiTxt.requestFocus();
        }
        else if(!mkMoi.equals(mkMoiXn)){           
            GUI.Main.thongBao("Mật khẩu xác nhận không chính xác", "Thông Báo", 1);
            xnMkNoiTxt.requestFocus();
        }
        else {
            if (capNhapMK(mkMoi)) {
                mkCuTxt.setText("");
                mkMoiTxt.setText("");
                xnMkNoiTxt.setText("");
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnxacNhanActionPerformed

    private void mkCuTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkCuTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mkCuTxtActionPerformed

    private void mkMoiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkMoiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mkMoiTxtActionPerformed

    private void xnMkNoiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xnMkNoiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xnMkNoiTxtActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmSinhVien frmSinhVien = new frmSinhVien(id_sv_23);
        frmSinhVien.show();
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDoiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnxacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField mkCuTxt;
    private javax.swing.JPasswordField mkMoiTxt;
    private javax.swing.JPasswordField xnMkNoiTxt;
    // End of variables declaration//GEN-END:variables
}
